//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paperspace.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paperspace.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;tgdcijpo&quot;,
        ///    &quot;name&quot;: &quot;paperspace/tgdcijpo&quot;,
        ///    &quot;label&quot;: &quot;H2O&quot;,
        ///    &quot;os&quot;: &quot;Ubuntu 16.04 Desktop&quot;,
        ///    &quot;dtCreated&quot;: &quot;2018-04-19T16:25:35.706Z&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;tibsmjg&quot;,
        ///    &quot;name&quot;: &quot;paperspace/tibsmjg&quot;,
        ///    &quot;label&quot;: null,
        ///    &quot;os&quot;: &quot;Ubuntu 16.04 Desktop&quot;,
        ///    &quot;dtCreated&quot;: &quot;2017-12-19T22:20:05.924Z&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;tpx5mr6b&quot;,
        ///    &quot;name&quot;: &quot;paperspace/tpx5mr6b&quot;,
        ///    &quot;label&quot;: &quot;RStudio&quot;,
        ///    &quot;os&quot;: &quot;Ubuntu 16.04 Desktop&quot;,
        ///    &quot;dtCreated&quot;: &quot;2018-04-06T02:55:42.105Z&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListTemplates {
            get {
                return ResourceManager.GetString("ListTemplates", resourceCulture);
            }
        }
    }
}
