pool:
  name: Hosted Ubuntu 1604
  
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '**/*'
    exclude:
      - README.md

pr:
  branches:
    include:
      - '*'
    exclude:
      - master
  paths:
    include:
      - '**/*'
    exclude:
      - README.md
  
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--no-restore --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: Create code coverage report
  inputs:
    reports: 'test/**/coverage.cobertura.xml'
    targetdir: CodeCoverage
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Xml'

  # Report code coverage to coveralls.io
- script: |
    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
    ./tools/csmacnz.Coveralls --reportgenerator -i "CodeCoverage/" --repoToken $(COVERALLS_REPO_TOKEN) --commitId "$(Build.SourceVersion)" --commitBranch "$(Build.SourceBranchName)" --commitAuthor "$(Build.RequestedFor)" --commitEmail "$(Build.RequestedForEmail)" --commitMessage "$(Build.SourceVersionMessage)" --jobId "$(Build.BuildId)" --useRelativePaths
  displayName: Publish code coverage report to coveralls

  # Publish the code coverage result (summary and web site)
  # The summary allows to view the coverage percentage in the summary tab
  # The web site allows to view which lines are covered directly in Azure Pipeline
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'CodeCoverage/Cobertura.xml'
    reportDirectory: 'CodeCoverage'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: src/Paperspace/Paperspace.csproj
    includesymbols: true

- task: DotNetCoreCLI@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    nuGetFeedType: external
    externalEndPoint: 'nuget.org'
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
